# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hours_To_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_start', models.IntegerField(verbose_name='Hours to work')),
                ('min_start', models.IntegerField(verbose_name='Minutes to work')),
            ],
        ),
        migrations.CreateModel(
            name='Punch_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_in', models.IntegerField(verbose_name='Clock in hour')),
                ('min_in', models.IntegerField(verbose_name='Clock in minute')),
            ],
        ),
        migrations.AddField(
            model_name='hours_to_work',
            name='punchIn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kc_app.Punch_In'),
        ),
    ]
