# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours_to_work',
            name='punchIn',
        ),
        migrations.AddField(
            model_name='punch_in',
            name='hr_start',
            field=models.IntegerField(default=0, verbose_name='Hours to work'),
        ),
        migrations.AddField(
            model_name='punch_in',
            name='min_start',
            field=models.IntegerField(default=0, verbose_name='Minutes to work'),
        ),
        migrations.AlterField(
            model_name='punch_in',
            name='hr_in',
            field=models.IntegerField(default=0, verbose_name='Clock in hour'),
        ),
        migrations.AlterField(
            model_name='punch_in',
            name='min_in',
            field=models.IntegerField(default=0, verbose_name='Clock in minute'),
        ),
        migrations.DeleteModel(
            name='Hours_To_Work',
        ),
    ]
